sudo: required
language: node_js
node_js:
  - "8"
  - "9"

services:
  - docker

before_script:
  - npm run build:dist
  - docker-compose up -d
  - npm run neo4j:wait

after_script:
  - npm run build:coverage:publish